/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    InventoryModal: typeof import('./src/components/InventoryModal.vue')['default']
    PriceProtectionModal: typeof import('./src/components/PriceProtectionModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TinyButton: typeof import('@opentiny/vue')['Button']
    TinyDialogBox: typeof import('@opentiny/vue')['DialogBox']
    TinyForm: typeof import('@opentiny/vue')['Form']
    TinyFormItem: typeof import('@opentiny/vue')['FormItem']
    TinyGrid: typeof import('@opentiny/vue')['Grid']
    TinyGridColumn: typeof import('@opentiny/vue')['GridColumn']
    TinyInput: typeof import('@opentiny/vue')['Input']
    TinyNumeric: typeof import('@opentiny/vue')['Numeric']
    TinyOption: typeof import('@opentiny/vue')['Option']
    TinySelect: typeof import('@opentiny/vue')['Select']
  }
}
